#!/bin/bash
set -eux 
if [ $# -eq 0 ]
  then
    act4e-test --collections act4e_checks --module act4e_solutions
else
if [ $# -eq 1 ]
  then
    act4e-test --collections act4e_checks --module act4e_solutions --group $1
else
    echo "Need to pass either 0 or 1 argument"
    exit 3
fi
fi


